# Generated by Django 5.0.2 on 2024-05-09 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], max_length=3)),
                ('division', models.CharField(choices=[('DEC', 'Dec'), ('QUA', 'Qua'), ('NONE', 'None')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SampleParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_time', models.DateTimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('repos_count', models.IntegerField()),
                ('min_members_count', models.IntegerField()),
                ('min_watch_count', models.IntegerField()),
                ('is_new_repos', models.BooleanField()),
                ('note', models.CharField(max_length=200, null=True)),
                ('avg_push_size_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avg_push_size_info', to='github_patterns_app.attributeinfo')),
                ('closed_issues_ratio_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_issues_ratio_info', to='github_patterns_app.attributeinfo')),
                ('forks_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forks_info', to='github_patterns_app.attributeinfo')),
                ('issues_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_info', to='github_patterns_app.attributeinfo')),
                ('merged_pull_requests_ratio_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_pull_requests_ratio_info', to='github_patterns_app.attributeinfo')),
                ('new_members_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_members_info', to='github_patterns_app.attributeinfo')),
                ('pull_requests_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests_info', to='github_patterns_app.attributeinfo')),
                ('pushes_duration_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pushes_info', to='github_patterns_app.attributeinfo')),
                ('watches_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches_info', to='github_patterns_app.attributeinfo')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=200, null=True)),
                ('pushes', models.IntegerField(null=True)),
                ('avg_push_size', models.FloatField(null=True)),
                ('pull_requests', models.IntegerField(null=True)),
                ('merged_pull_requests_ratio', models.FloatField(null=True)),
                ('issues', models.IntegerField(null=True)),
                ('closed_issues_ratio', models.FloatField(null=True)),
                ('watches', models.IntegerField(null=True)),
                ('forks', models.IntegerField(null=True)),
                ('new_members', models.IntegerField(null=True)),
                ('language', models.CharField(max_length=200, null=True)),
                ('license_name', models.CharField(max_length=200, null=True)),
                ('is_deleted_or_private', models.BooleanField(null=True)),
                ('data_params_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='githubdata_set', to='github_patterns_app.sampleparams')),
            ],
        ),
    ]
